spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/mozhe24/spring-cloud-config
          search-paths: respo
          username: 1037444979@qq.com
          password: caodongjian1234
#GitHub https://github.com/mozhe24/spring-cloud-config/respo目录
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/